# Site settings
title:  Sussex Stairs
email: sales@sussexstairs.co.uk
telephone: 01483 506390
fax: 01483 431967
mobile: 07778 762190
description: "Sussex Stairs"
baseurl: ""
url: "http://sussexstairs.co.uk"

# Build settings
markdown: redcarpet
permalink: pretty
exclude : ['vendor', 'Gemfile*', 'bin', 'README.md']
